---
# tasks file for install prosody on Debian and Ubuntu systems
- name: Install Prosody
  apt: name=prosody state=present
  
- name: Install Mercurial (For Prosody community modules)
  apt: name=mercurial state=present
  when: prosody_install_community_modules

- name: Install lua-event (If needed)
  apt: name=lua-event state=present
  when: prosody_install_lua_event
  notify: restart prosody

- name: Install lua-zlib (If needed)
  apt: name=lua-zlib state=present
  when: prosody_install_lua_zlib
  notify: restart prosody

- name: Install lua-ldap (If needed)
  apt: name=lua-ldap state=present
  when: prosody_install_lua_ldap
  notify: restart prosody

- name: Install Sqlite support in Lua. Needed for Conversation XMPP Client (MAM module).
  apt: name=lua-dbi-sqlite3 state=present
  when: prosody_enable_conversations_XEPs or prosody_storage == "sqlite"
  notify: restart prosody