---
# tasks file for install Prosody on Fedora, CentOS and Red-Hat systems
- name: Install EPEL (If specified and needed)
  yum:
    name: epel-release
    state: latest
  when: prosody_install_epel and ansible_distribution == 'CentOS'
  
- name: Install Prosody
  yum:
    name: prosody
    state: latest
  
- name: Install Mercurial (For Prosody community modules)
  yum:
    name: mercurial
    state: latest
  when: prosody_install_community_modules

- name: Install Prosody community modules
  hg:
    repo: "{{ prosody_community_modules_repo }}"
    dest: "{{ prosody_community_modules_directory }}"
    purge: yes
  when: prosody_install_community_modules
  notify: restart prosody
  
- name: Install lua-event (If needed)
  yum:
    name: lua-event
    state: latest
  when: prosody_install_lua_event
  notify: restart prosody
  
- name: Install lua-zlib (If needed)
  yum:
    name: lua-zlib
    state: latest
  when: prosody_install_lua_zlib
  notify: restart prosody

- name: Install lua-ldap (If needed)
  yum:
    name: lua-ldap
    state: latest
  when: prosody_install_lua_ldap
  notify: restart prosody

- name: Install Sqlite support in Lua. Needed for Conversation XMPP Client (MAM module).
  yum:
    name: lua-dbi
    state: latest
  when: prosody_enable_conversations_XEPs or prosody_storage == "sqlite"
  notify: restart prosody
